### ISSUE TITLE
label of vertices?

### ISSUE THREAD

**Issue by TunahanCATAK** [liulihui/Ullmann#2]
Hi, 

I've just started to work on sub graph matching algorithms and I thought that Ullmanns' algorithm will be the best starting point. While I was searching network I found your repos. But I couldn't understand one point of your graph database, why are you using labels for vertices? Because of, I couldn't seen any things like label in original paper of Ullmann. 

If you can find to time to response my problem, I'd be pleasure. 

Regards,
Tunahan.

**Comment by hucaser** [comment]
@TunahanCATAK Thanks for your interest on my code. Although Ullmann algorithm does not use labels for vertices, there are many other algorithm use labels for vertices, these labels are used by other algorithms. You can ignore these labels.

**Comment by TunahanCATAK** [comment]
Thanks for your fast response. Also how do you check your codes' correctness?

**Comment by hucaser** [comment]
@TunahanCATAK I wrote these code several years ago, and many details I couldn't remember exactly. But I truely run this code on some small datasets. Maybe there are some mistakes in the result.
